[application]

# Desktop app configuration
[application.desktop]

# The name of the app
name = "RustySound"

# The icon to use for the app (PNG, ICNS, or ICO)
icon = "assets/logo.png"

# Mobile app configuration  
[application.mobile]

# The name of the app
name = "RustySound"

# The icon to use for the app (PNG)
icon = "assets/logo.png"

[web.app]

# HTML title tag content
title = "RustySound"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
